# Generated by Django 4.1.1 on 2022-10-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
