# Generated by Django 4.1.1 on 2022-10-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='N', max_length=1)),
                ('type', models.CharField(choices=[('N', 'NO ONE'), ('O', 'ONE MONTH'), ('T', 'THREE MONTH'), ('S', 'SIX MONTH')], default=None, max_length=1)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
            ],
        ),
    ]
