# Generated by Django 4.1.1 on 2022-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_code',
            field=models.CharField(default='1233', max_length=6),
            preserve_default=False,
        ),
    ]
