# Generated by Django 4.1.1 on 2022-10-31 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_active_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_code',
        ),
    ]
