# Generated by Django 4.1.3 on 2022-11-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
    ]
