# Generated by Django 3.2.16 on 2022-11-12 15:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'فیلم', 'verbose_name_plural': 'فیلم ها'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.AddField(
            model_name='movie',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='نام فیلم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='film/movies', verbose_name='عکس'),
        ),
    ]
